version: '3.3'
services:
  autopsy:
    image: "autopsy:latest"
    container_name: autopsy
    shm_size: "2gb"
    environment:
      - DISPLAY=${DISPLAY}
      - JAVA_TOOL_OPTIONS=-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - "./case/:/home/app/case"
    network_mode: host
    devices:
      - "/dev/dri:/dev/dri"
